//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("OpenModulePlatform")]
[assembly: System.Reflection.AssemblyCopyrightAttribute(" ")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1.0+8b1f5008f9c27b5784c60310a285602c9ef60004")]
[assembly: System.Reflection.AssemblyProductAttribute("OpenModulePlatform")]
[assembly: System.Reflection.AssemblyTitleAttribute("OpenModulePlatform.Web.ExampleWebAppBlazorModule")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.1.0.0")]
[assembly: System.Reflection.AssemblyCultureAttribute("en")]

// Generated by the MSBuild WriteCodeFragment class.

